@startuml
skinparam linetype ortho
skinparam ranksep 35
skinparam nodesep 25

|Trenér|
start
:Vytvořit novou událost;

|Systém|
:Publikovat událost;

if (Událost je zápas?) then (Ano)
:Odeslat upozornění hráčům;
else (Ne)
endif

|Hráč|
:Zobrazí událost v aplikaci;
:Rozhodne se o účasti;

if (Zúčastní se?) then (Ano)
:Potvrdí účast;
else (Ne)
:Odmítne účast;
endif

|Systém|
:Aktualizuje seznam účasti;

|Trenér|
:Zkontroluje přehled účasti hráčů;

while (Dostatek hráčů?) is (Ne)
  if (Pozvat další hráče?) then (Ano)
    :Pozve další hráče;

    |Systém|
    :Přidá nové hráče do události;

    if (Událost je zápas?) then (Ano)
      :Odešle upozornění nově přidaným hráčům;
    else (Ne)
    endif

    |Hráč|
    :Zobrazí událost v aplikaci;
    :Rozhodne se o účasti;

    if (Zúčastní se?) then (Ano)
    :Potvrdí účast;
    else (Ne)
    :Odmítne účast;
    endif

    |Systém|
    :Aktualizuje seznam účasti;

    |Trenér|
    :Zkontroluje přehled účasti hráčů;

  else (Ne)
    |Systém|
    :Zruší událost;
    :Informuje hráče o zrušení;
    stop
  endif
endwhile (Ano)

|Trenér|
:Potvrdí sestavu události;

stop
@enduml
